### ISSUE TITLE
plz ad autoarmor back

### ISSUE THREAD

**Issue by pawa2401** [AmoClub/lbplusplus_new#14]
its very needed sir i need it
skid it from somewhere or add the liqudbounce one back (or both)

**Comment by HaLa248** [comment]
invmanager

**Comment by pawa2401** [comment]
> invmanager

Yeah but it doesn't seem to work that well from my experience. I see it doing something with the armor but...
1. It tries to put worse armor on (Chain helmet over Iron)
2. It doesn't do it in the end
3. No matter if WearArmor is on or off it tries to put the helmet on
4. No additional settings (I don't remember if liquidbounce has any, but there is room for improvement since this is the plus plus version)
5. Also having it as a seperate option allows for keybing these two modules separately

**Comment by syskill-the-coder** [comment]
> its very needed sir i need it skid it from somewhere or add the liqudbounce one back (or both)

1. fork it
2. go to the liquidbounce original github
3. ctrl c
4. ctrl v

**Comment by TheMosKau** [comment]
> > invmanager
> 
> Yeah but it doesn't seem to work that well from my experience. I see it doing something with the armor but...
> 
> 1. It tries to put worse armor on (Chain helmet over Iron)
> 2. It doesn't do it in the end
> 3. No matter if WearArmor is on or off it tries to put the helmet on
> 4. No additional settings (I don't remember if liquidbounce has any, but there is room for improvement since this is the plus plus version)
> 5. Also having it as a seperate option allows for keybing these two modules separately

sorry for not reading this issue, i'll try to fix this lol
