### ISSUE TITLE
Want to adapt to minecraft version 1.12.2 forge

### ISSUE THREAD

**Issue by KrOik** [AmoClub/lbplusplus_new#22]
The long-awaited reply and clear intention are appreciated

**Comment by f4r2** [comment]
Why u need this?

**Comment by KrOik** [comment]
Hello, I'm very glad to get your attention. Thank you very much. I will elaborate on the reasons for my request as much as possible
In our community, there are many servers of 1.12.2 that need to be adapted. Since the server has taken relevant measures, many players have to switch from 1.8.9 to 1.12.2 to adapt to the newly added mods and related files so as to bypass the game. This has created an impassable barrier for authors and configurators (? Is this the name). Therefore, I have issued this adaptation request to hope that someone can fill the vacancy of 1.12.2 - related branch support in liquid bounce. If this is implemented, it will be a new rebirth for version 1.12.2. Of course, it is source code support.
From the translation software, there are some strange tones and sentences, please forgive and tolerate, thank you!

**Comment by f4r2** [comment]
Oh u are russian? I speak russian too. Probably liquidbounce++ will not get ported for 1.12.2 , but u can try to use ViaForge https://www.curseforge.com/minecraft/mc-mods/viaforge/files. Or u can use original liquidbounce 1.12.2. It is updated to b73 rn

**Comment by TheHackerLxr** [comment]
i want fixed scripts in Liquidbounce 1.12.2 some scripts just don't work

**Comment by TheMosKau** [comment]
> Oh u are russian? I speak russian too. Probably liquidbounce++ will not get ported for 1.12.2 , but u can try to use ViaForge https://www.curseforge.com/minecraft/mc-mods/viaforge/files. Or u can use original liquidbounce 1.12.2. It is updated to b73 rn

thanks for explaining it to him!
