### ISSUE TITLE
Error when setting a workspace.

### ISSUE THREAD

**Issue by Pelqsita** [AmoClub/lbplusplus_new#27]
I get an error when I put gradlew setupDevWorkspace idea genIntellijRuns build please help :(
![image](https://user-images.githubusercontent.com/77317681/229853495-6fae31eb-bf16-4707-84b0-bfdb48b3b7d5.png)

**Comment by emilia-montauban** [comment]
same :P

**Comment by enuxx** [comment]
same :/

**Comment by TheMosKau** [comment]
This will be fixed soon, sorry for not replying.

**Comment by TheMosKau** [comment]
For now i will pin this issue so that people will know im fixing it.

**Comment by TheMosKau** [comment]
This should be fixed, please fetch the change.
How to fetch:
Github Desktop:
![gbdesktop](https://github.com/PlusPlusMC/LiquidBouncePlusPlus/assets/77763580/1d1499e2-4f64-4fe4-ba83-7ad614d74bbe)

Github Site:
![gbsite](https://github.com/PlusPlusMC/LiquidBouncePlusPlus/assets/77763580/8db04c57-d1b8-4df8-ac5d-f36a9ce44af5)

Terminal/Command Prompt:
git pull

**Comment by TheMosKau** [comment]
if something isn't working, please let me know.
