### ISSUE TITLE
ScriptManager problem

### ISSUE THREAD

**Issue by ghost** [AmoClub/lbplusplus_new#35]
How to replicate:

1. do .t or .toggle scriptmanager in chat

2. game will proceed to crash.

the same thing occurs when trying to access scriptmanager via the main menu too.

Error:

The game crashed whilst rendering screen
Error: kotlin.UninitializedPropertyAccessException: lateinit property scriptManager has not been initialized

Also occurs on MultiMC (first suspected it was a multimc issue, turns out its not)

**Comment by TheMosKau** [comment]
I think i've fixed it
please go download LiquidBounce++ again (https://plusplus.themoskau.xyz)

**Comment by TheMosKau** [comment]
I am closing the issue now
