### ISSUE TITLE
1.19 support for the version switcher

### ISSUE THREAD

**Issue by terminated-star** [AmoClub/lbplusplus_new#9]
I would like to join 1.19 servers ty

**Comment by SnooComics9452** [comment]
Never, since mos is discontinued lb++

**Comment by terminated-star** [comment]
> Never, since mos is discontinued lb++

You sure? Their last commit was 13 hours ago.

**Comment by SnooComics9452** [comment]
I am joking but I am sure that the lb++ 0.3 plubic release will be released in next year because mos moment

**Comment by TheMosKau** [comment]
Added
